server:
  servlet:
    context-path: /auth
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://192.168.1.54:3306/sso_demo?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # com.mysql.jdbc.Driver Spring Boot 2.1.0 之前用这个  com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false

  redis:
    database: 0
    host: 192.168.1.54
    port: 6379
    password:
    timeout: 3s
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 0
        max-wait: 3s

#security:
#  oauth2:
#    personal:
#      registered-redirect-uri: http://localhost:18082/login

logging:
  path: D:\logs\sso_demo\auth-center